### ISSUE TITLE
Script execution failed on Windows

### ISSUE THREAD

**Issue by PeacefulPieDev** [acsbendi/Build-SFML-For-Android-On-Windows#1]
Hello.
I'm, trying to use your scripts to build SFML, after I lost hope with official guide.

Thank's a lot, I've build succesfully libs once, but it required to use some commands from your scripts manually. Unfortunately, next attempts to reproduce those steps were unsuccesfull.

Currently, build-sfml.bat fails with next message:
`D:\SFML Build>build-sfml.bat C:\AndroidNDK\`
`Downloading SFML to C:\Users\nikita.smirnov\SFML`
`fatal: destination path 'SFML' already exists and is not an empty directory`
`The system cannot find the file specified.`
`Error occurred while processing: D:\SFML.`
`The system cannot find the path specified.`
`The system cannot find the file specified.`
`Error occurred while processing: D:\SFML.`
`The system cannot find the path specified.`
`Invalid number of parameters`
`'C:\Users\nikita.smirnov\SFML\SFML\build\rebuild-all.bat' is not recognized as an internal or external`
`command, operable program or batch file.`
`D:\SFML Build>`
Don't mind with not-empy SFML, it's because I'm running the script second time. Seems problems appear when the script trying to exclude arm64 and x86_64.

I would be very grateful for any kind of help or advice.

**Comment by acsbendi** [comment]
Hi, 
You're welcome :)
If you want to build it again after your first successful build, you just have to execute `<SFML-dir>\build\rebuild-all.bat` and it is supposed to rebuild SFML.
Otherwise you can use `build-sfml.bat` again, but providing a different path for SFML, for example: `build-sfml.bat C:\AndroidNDK\ C:\Users\nikita.smirnov\SFML2`.
arm64 and x86_64 should not caused any issues, they are excluded from the build (because SFML does not seem to support them currently).

**Comment by acsbendi** [comment]
Closing this, if the problem persists, feel free to reopen or send a comment.
